name: Coverage

on: pull_request

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: make test-unit

      - name: Generate App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Code Coverage Annotations
        uses: MichaelDyeTryout/codecoverage@352f7a849966937a87c306ab5d54d02d527369a8
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          COVERAGE_FILE_PATH: coverage.out
          COVERAGE_FORMAT: go
          DEBUG: coverage,pr_lines_added
