name: Coverage

on: pull_request

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: make test-unit

      - name: Code Coverage Annotations
        uses: MichaelDyeTryout/codecoverage@5c21f66d7576ea771d0a9721de2282c754914884
        with:
          GITHUB_TOKEN: ${{secrets.PR_ANNOTATION_TOKEN}}
          COVERAGE_FILE_PATH: coverage.out
          COVERAGE_FORMAT: go
          DEBUG: coverage,pr_lines_added
