name: Coverage

on: pull_request

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: make test-unit

      - name: Code Coverage Annotations
        uses: MichaelDyeTryout/codecoverage@2444b4b7f6951fb6fee5696a41e5b956409d839a
        with:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          COVERAGE_FILE_PATH: coverage.out
          COVERAGE_FORMAT: go
          DEBUG: coverage,pr_lines_added
